#!/usr/bin/env python3
"""Generate the core/ indexes from disk (v4 architecture, D4).

Summary: scans the repo and the global ~/.claude agent/skill dirs and writes
the generated, read-only cache files under core/: PROJECT_MAP.md (code map),
agent_chart.md (roster index), skills_index.md (catalogue index). These are
the files a fresh session loads at token zero instead of calling Notion.

When to touch: never edit the OUTPUT files by hand (they are regenerated and
will overwrite). Edit THIS script to change what is captured, or the
hand-maintained core/WORKSPACE_MAP.md and core/charter.md which this script
does not touch.

Run: python scripts/update_project_map.py
Single writer: writes only into core/. Reads everything else.
"""

from __future__ import annotations

import os
import re
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# Path resolution. Repo root = parent of this script's folder. Home resolved
# dynamically (no hardcoded machine path), so this stays repo/user agnostic.
# ---------------------------------------------------------------------------
REPO = Path(__file__).resolve().parent.parent
CORE = REPO / "core"
HOME = Path(os.path.expanduser("~"))
GLOBAL_AGENTS = HOME / ".claude" / "agents"
GLOBAL_SKILLS = HOME / ".claude" / "skills"
REPO_AGENTS = REPO / ".claude" / "agents"
REPO_SKILLS = REPO / ".claude" / "skills"

STAMP = date.today().isoformat()
GENERATED_NOTE = (
    f"> GENERATED by scripts/update_project_map.py on {STAMP}. Read-only cache.\n"
    "> Do not edit by hand. Run the script to refresh. Source of truth on disk.\n"
)

# One-line purposes for known repo folders. Unknown folders show "(undocumented)".
# Grow this dict as folders earn a description; it is the only hand-curated bit.
FOLDER_PURPOSE = {
    "OS": "AI operating-system architecture docs (source of truth for how the agent system runs)",
    "core": "Generated read-only cache loaded at token zero: maps, roster, skills index, charter",
    "evals": "Machine (binary + cost) and content (lint + human gate) tests",
    "scripts": "Build and maintenance scripts, incl. this map generator",
    "website": "The sonagibeauty site source",
    "netlify": "Netlify deploy config and edge functions",
    "brand-strategy": "Working brand docs (largely untracked; OneDrive mirror is backup)",
    "content": "Content plans and drafts (largely untracked)",
    "media": "Local media working files",
    "images": "Dated asset folders (images/YYYY-MM-DD)",
    "docs": "Project documentation",
    ".claude": "Project-local Claude config: repo agents, skills junctions, commands",
    ".agents": "Source skill packs junctioned into .claude/skills",
}

FRONTMATTER = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)


def read_text(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def clean(s: str) -> str:
    """Strip banned em-dash characters from mirrored upstream text so the
    generated cache always passes the em-dash gate. Built from code points so
    this generator's own source contains no banned literal."""
    return s.replace(chr(0x2014), ", ").replace(chr(0x2015), ", ").replace("  ", " ")


def parse_frontmatter(text: str) -> dict:
    """Return a dict of the YAML frontmatter, handling folded/block scalars.

    Handles `key: value`, and `key: >` or `key: |` followed by indented
    continuation lines (used by the ads agents for long descriptions).
    """
    m = FRONTMATTER.match(text)
    if not m:
        return {}
    out: dict = {}
    lines = m.group(1).splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if ":" in line and not line.lstrip().startswith("#") and not line.startswith((" ", "\t")):
            k, _, v = line.partition(":")
            key, val = k.strip(), v.strip()
            if val in (">", "|", ">-", "|-"):
                # block scalar: gather the indented lines that follow
                block = []
                i += 1
                while i < len(lines) and (lines[i].startswith((" ", "\t")) or lines[i].strip() == ""):
                    block.append(lines[i].strip())
                    i += 1
                out[key] = " ".join(b for b in block if b).strip()
                continue
            out[key] = val
        i += 1
    return out


def first_tier(text: str) -> str:
    """Pull a 'Tier N' mention if the agent declares one, else blank."""
    m = re.search(r"\bTier\s*([0-2])\b", text)
    return f"T{m.group(1)}" if m else ""


# ---------------------------------------------------------------------------
# PROJECT_MAP.md: top-level repo folders, file counts, key entry files.
# ---------------------------------------------------------------------------
def gen_project_map() -> str:
    rows = []
    for child in sorted(REPO.iterdir(), key=lambda p: p.name.lower()):
        if child.name == ".git":
            continue
        if child.is_dir():
            try:
                n = sum(1 for _ in child.rglob("*") if _.is_file())
            except OSError:
                n = 0
            purpose = FOLDER_PURPOSE.get(child.name, "(undocumented)")
            rows.append(f"| `{child.name}/` | {n} | {purpose} |")
    key_files = [
        f for f in ("CLAUDE.md", "AGENTS.md", "README.md", "netlify.toml", "package.json", "deno.lock")
        if (REPO / f).exists()
    ]
    body = [
        "# PROJECT_MAP.md: repo code map\n",
        GENERATED_NOTE,
        "\nSummary: every top-level folder of the sonagi-beauty repo, its file "
        "count, and its one-line purpose. Use it to locate work without scanning.\n",
        "\n## Top-level folders\n",
        "| Folder | Files | Purpose |",
        "| --- | --- | --- |",
        *rows,
        "\n## Key root files\n",
        ", ".join(f"`{f}`" for f in key_files) if key_files else "(none)",
        "",
    ]
    return "\n".join(body)


# ---------------------------------------------------------------------------
# agent_chart.md: every agent from global + repo dirs (name, job, tier, path).
# ---------------------------------------------------------------------------
def collect_agents() -> list[dict]:
    agents = []
    for root, scope in ((GLOBAL_AGENTS, "global"), (REPO_AGENTS, "repo")):
        if not root.exists():
            continue
        for p in sorted(root.rglob("*.md")):
            if p.name.lower() == "readme.md":
                continue
            text = read_text(p)
            fm = parse_frontmatter(text)
            if not fm.get("name"):
                continue
            runtime = "~/.claude/agents/" + p.relative_to(root).as_posix() if scope == "global" \
                else p.relative_to(REPO).as_posix()
            agents.append({
                "name": fm.get("name", p.stem),
                "job": fm.get("description", "").strip(),
                "tier": first_tier(text),
                "scope": scope,
                "runtime": runtime,
            })
    return agents


def gen_agent_chart(agents: list[dict]) -> str:
    rows = []
    for a in sorted(agents, key=lambda x: x["name"].lower()):
        job = clean(a["job"])
        if len(job) > 130:
            job = job[:127] + "..."
        rows.append(
            f"| `{a['name']}` | {a['tier'] or '-'} | {a['scope']} | {job} | `{a['runtime']}` |"
        )
    return "\n".join([
        "# agent_chart.md: agent roster index\n",
        GENERATED_NOTE,
        f"\nSummary: every agent definition on disk ({len(agents)} found). "
        "Pick agents from here, never by scanning. Canonical human roster: "
        "Notion AI Operations & Agent Architecture.\n",
        "\nNote: Tier is read from the agent file's text. It is a LABEL until the "
        "clean-run counter exists (core/agent_ledger.md, not yet built).\n",
        "\n| Agent | Tier | Scope | Job | Runtime path |",
        "| --- | --- | --- | --- | --- |",
        *rows,
        "",
    ])


# ---------------------------------------------------------------------------
# skills_index.md: bounded scan. A dir with its own SKILL.md is a skill; a dir
# that only contains sub-skills is a pack (counted, not inlined). Depth capped
# to avoid following Windows junctions into huge or looping trees.
# ---------------------------------------------------------------------------
def skill_meta(skill_dir: Path) -> tuple[str, str]:
    sk = skill_dir / "SKILL.md"
    fm = parse_frontmatter(read_text(sk)) if sk.exists() else {}
    name = fm.get("name", skill_dir.name)
    desc = clean(fm.get("description", "").strip().replace("\n", " "))
    if len(desc) > 120:
        desc = desc[:117] + "..."
    return name, desc


def scan_skill_root(root: Path) -> tuple[list[tuple[str, str]], list[tuple[str, int]]]:
    """Return (single_skills, packs). Bounded to two levels under root."""
    singles, packs = [], []
    if not root.exists():
        return singles, packs
    for child in sorted(root.iterdir(), key=lambda p: p.name.lower()):
        if not child.is_dir():
            continue
        if (child / "SKILL.md").exists():
            singles.append(skill_meta(child))
        else:
            # count SKILL.md one level down only (a pack of skills)
            try:
                count = sum(1 for sub in child.iterdir() if sub.is_dir() and (sub / "SKILL.md").exists())
            except OSError:
                count = 0
            packs.append((child.name, count))
    return singles, packs


def gen_skills_index() -> str:
    parts = [
        "# skills_index.md: skills catalogue index\n",
        GENERATED_NOTE,
        "\nSummary: skills available on disk. Single skills are listed with their "
        "trigger description; multi-skill packs are listed by name and count (not "
        "inlined, to keep the cold start light). Open a pack's folder for its "
        "members. Canonical human catalogue: Notion Skills Catalogue.\n",
    ]
    for label, root in (("Global (~/.claude/skills)", GLOBAL_SKILLS),
                        ("Repo (.claude/skills)", REPO_SKILLS)):
        singles, packs = scan_skill_root(root)
        parts.append(f"\n## {label}\n")
        if singles:
            parts.append("### Single skills\n")
            parts.append("| Skill | What it does (trigger) |")
            parts.append("| --- | --- |")
            for name, desc in sorted(singles):
                parts.append(f"| `{name}` | {desc or '(no description)'} |")
        if packs:
            parts.append("\n### Packs (folder : skill count)\n")
            parts.append("| Pack | Skills |")
            parts.append("| --- | --- |")
            for name, count in sorted(packs):
                parts.append(f"| `{name}/` | {count} |")
        if not singles and not packs:
            parts.append("(none found)")
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    CORE.mkdir(exist_ok=True)
    agents = collect_agents()
    outputs = {
        "PROJECT_MAP.md": gen_project_map(),
        "agent_chart.md": gen_agent_chart(agents),
        "skills_index.md": gen_skills_index(),
    }
    for fname, content in outputs.items():
        (CORE / fname).write_text(content, encoding="utf-8")
        print(f"wrote core/{fname} ({len(content)} bytes)")
    print(f"agents indexed: {len(agents)}")


if __name__ == "__main__":
    main()
